//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSDeneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int IMAGE_ID { get; set; }
        public string IMAGE_URL { get; set; }
        public string IMAGE_ALT { get; set; }
    }
}
