//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSDeneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public int VIDEO_ID { get; set; }
        public string VIDEO_BASLIK { get; set; }
        public string VIDEO_URL { get; set; }
    }
}
